name: Auto Commit Activity

on:
  schedule:
    - cron: '0 0 * * *' # هر روز سر ساعت مشخص اجرا می‌شود
  workflow_dispatch: # برای اینکه بتوانید دستی هم اجرا کنید

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "AM-mirzanejad"
          git config --global user.email "am.mirzanejad@gmail.com"

      - name: Make Changes and Commit
        run: |
          echo "$(date)" >> activity.txt
          git add activity.txt
          git commit -m "Daily automated commit" || exit 0
          git push
