name: Auto Commit Activity

on:
  schedule:
    - cron: '0 0 * * *' # Executes daily at midnight UTC
  workflow_dispatch: # Allows for manual triggering

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure Git
        run: |
          git config --global user.name "AM-mirzanejad"
          git config --global user.email "am.mirzanejad@gmail.com"

      - name: Run Activity Simulator
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          python activity_simulator.py
